# Generated by Django 5.1.2 on 2024-11-02 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session_stats', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessionstats',
            old_name='heart_rate',
            new_name='BPM',
        ),
    ]
