# Generated by Django 5.1.2 on 2024-11-03 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session_stats', '0004_alter_sessionstats_bpm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionstats',
            name='distance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sessionstats',
            name='g',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sessionstats',
            name='pace',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
