# Generated by Django 5.1.2 on 2024-11-01 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='concussion_risk',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
