# Generated by Django 5.1.2 on 2024-10-27 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("session", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateTimeField()),
                ("accel_x", models.FloatField()),
                ("accel_y", models.FloatField()),
                ("accel_z", models.FloatField()),
                ("quat_w", models.FloatField()),
                ("quat_x", models.FloatField()),
                ("quat_y", models.FloatField()),
                ("quat_z", models.FloatField()),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="session.session",
                    ),
                ),
            ],
            options={
                "db_table": "BNO055_chest",
                "ordering": ["time"],
            },
        ),
    ]
