# Generated by Django 5.1.2 on 2024-11-01 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('left_leg', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leftleg',
            old_name='session',
            new_name='session_id',
        ),
    ]
