# Generated by Django 5.1.2 on 2024-11-03 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardstats',
            name='concussion_passeport',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dashboardstats',
            name='concussion_risk',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dashboardstats',
            name='heart_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dashboardstats',
            name='rest_days',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dashboardstats',
            name='training_intensity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dashboardstats',
            name='training_productivity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
