# Generated by Django 5.1.2 on 2024-11-01 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('session', '0003_remove_session_acceleration_max_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConcussionStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('footing_quality', models.FloatField()),
                ('number_of_shocks', models.IntegerField()),
                ('max_g', models.FloatField()),
                ('heart_rate', models.FloatField()),
                ('SpO2', models.FloatField()),
                ('temperature', models.FloatField()),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='session.session')),
            ],
            options={
                'db_table': 'concussion_stats',
                'ordering': ['time'],
            },
        ),
    ]
