# Generated by Django 5.1.2 on 2024-11-02 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concussion_stats', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='concussionstats',
            old_name='heart_rate',
            new_name='BMP',
        ),
    ]
