# Generated by Django 5.1.2 on 2024-11-03 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concussion_stats', '0002_rename_heart_rate_concussionstats_bmp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concussionstats',
            name='BMP',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='concussionstats',
            name='SpO2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='concussionstats',
            name='footing_quality',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='concussionstats',
            name='max_g',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='concussionstats',
            name='number_of_shocks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='concussionstats',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
