# Generated by Django 5.1.2 on 2024-11-01 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('session', '0002_alter_session_concussion_risk'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeftLegTransformed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('accel_x', models.FloatField()),
                ('accel_y', models.FloatField()),
                ('accel_z', models.FloatField()),
                ('vel_x', models.FloatField()),
                ('vel_y', models.FloatField()),
                ('vel_z', models.FloatField()),
                ('pos_x', models.FloatField()),
                ('pos_y', models.FloatField()),
                ('pos_z', models.FloatField()),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='session.session')),
            ],
            options={
                'db_table': 'BNO055_left_leg_transformed',
                'ordering': ['timestamp'],
            },
        ),
    ]
